# -*- coding: utf-8 -*-
"""Keerthana airline data analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTTnm5gule1urONTvC361mN8oaIUGEFY

Day 1
"""

# Import required libraries
import numpy as np
import pandas as pd

print("Numpy imported successfully")
print("Pandas imported successfully")

import os
os.getcwd()

from google.colab import files
import pandas as pd

uploaded = files.upload()
df_airline = pd.read_csv("airlines_flights_data.csv")
df_airline.head()

#display first 5 rows
df_airline.head()

# Diplay last 5 rows
df_airline.tail()

"""

*Day 2 task : Load Dataset Airline and apply all the pandas operations*"""

from google.colab import files
import pandas as pd

uploaded = files.upload()
df_airline = pd.read_csv("airlines_flights_data.csv")
df_airline.head()

#code1
df_airline.head()

#code2
df_airline.tail()

#code3
df_airline.shape

#code4
df_airline.columns

#code 5
df_airline.dtypes

#code6
df_airline.info()

#code 7
df_airline.describe()

#code 8
df_airline["airline"]

#code9
df_airline[["airline","flight"]]

#code10
df_airline.loc[:,:]

#code11
df_airline.iloc[:,:]

#code12
df_airline[df_airline["price"] > 10000]

#code13
df_airline["airline"].unique()

#code14
df_airline["airline"].value_counts()

#code 15
df_airline["price"].sum()

#code 16
df_airline["price"].mean()

#code 17
df_airline["price"].max()

"""Day 3"""

from google.colab import files
import pandas as pd

uploaded = files.upload()
df_airline = pd.read_csv("airlines_flights_data.csv")
df_airline.head()

"""

> *Task 1: Inspect the airline dataset and display First 10 rows Last 10 rows Number of rows and columns All the column names*"""

#code
display(df_airline.head(10))

display(df_airline.tail(10))

print("Shape:", df_airline.shape)

print("Columns:")
print(df_airline.columns.tolist())

"""

> *Task 2: Select important flight columns and display first 10 records names of the columns namely airline source_city destination_city class duration price*"""

# code
df_airline[
    ["airline", "source_city", "destination_city", "class", "duration", "price"]
].head(10)

"""
> Task 3: Find expensive flights, where price is greater than 20000. Display the 10 records."""

# code
expensive_flights = df_airline[df_airline["price"] > 20000]

print("Number of Flights:", len(expensive_flights))

display(expensive_flights.head(10))

"""

> *Task 4: Filter by airline. Find flights operated uniquely.*"""

#code
flights_by_airline = df_airline.groupby('airline')['flight'].unique()

print(flights_by_airline)

"""

> *Task 5: Filter by class. Find flights belonging to the economy class*"""

# code
economy_flights = df_airline[df_airline['class'] == 'Economy']

print(economy_flights)

"""
> Task 6: Multiple Conditions Find flights where price is greater than 50000 and duration is greater than 10 hours."""

# code

result = df_airline[
    (df_airline["price"] > 50000) &
    (df_airline["duration"] > 10)
]

display(result.head())

"""

> *Task 7: Airline distribution. Find Unique airlines Number of airlines Number of flights for each airline*"""

# code

print("airline:")
print(df_airline["airline"].unique())

print("\nNumber of airline:")
print(df_airline["airline"].nunique())

print("\nNumber of flights for each airline:")
print(df_airline["airline"].value_counts())

"""

> *Task 10: Duration Analysis. Calculate Total duration Average duration Median duration Maximum duration Minimum duration*"""

# code

print("Total duration:", df_airline["duration"].sum())
print("Average duration:", df_airline["duration"].mean())
print("Median duration:", df_airline["duration"].median())
print("Maximum duration:", df_airline["duration"].max())
print("Minimum duration:", df_airline["duration"].min())

"""Day 4&5"""

# AIRLINE  DATASET

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohitgrewal/airlines-flights-data")

print("Path to dataset files:", path)


import os

print(os.listdir(path))


import pandas as pd

df = pd.read_csv(os.path.join(path, "airlines_flights_data.csv"))

print( "Dataset loaded successfully")

import kagglehub
import pandas as pd
import os

# Download the exact dataset
path = kagglehub.dataset_download("rohitgrewal/airlines-flights-data")

print("Dataset path:", path)
print("Files:", os.listdir(path))

# Load CSV
df_airline = pd.read_csv(
    os.path.join(path, "airlines_flights_data.csv")
)

print("Dataset loaded successfully")
print(df_airline.head())
print(df_airline.info())
print(df_airline.columns.tolist())

"""Task 1: Single-Column Groupby Aggregation.                                 
Question: Calculate the average departure delay for each airline carriers.
"""

# Task 1: Single-Column Groupby Aggregation

airline_col = 'airline'
dep_col = 'departure_time'
origin_col = 'source_city'
dest_col = 'destination_city'

task1_airline = df.groupby(airline_col)[dep_col].count().reset_index(name='departure_count')

print(task1_airline.head(5))

"""Task 2: Multi-Column Groupby Aggregation"""

#code
task2_airline = df_airline.groupby([origin_col, dest_col]).agg(
    Flight_Count=(dep_col, 'count')
).reset_index()

print(task2_airline.head(5))

"""Task 3: Multi-Metric Aggregation with agg()"""

#code
task3_airline = df_airline.groupby(airline_col).agg(
    Total_Flight_Count=(dep_col, 'count')
).reset_index()

print(task3_airline.head(5))

"""Task 4: Sorting Aggregated Summaries"""

#code
task4_airline = (df_airline.groupby(origin_col)
                 .size()
                 .reset_index(name='Total_Flights')
                 .sort_values(by='Total_Flights', ascending=False)
                 .head(5))

print(task4_airline)

"""Task 5: Named Aggregations"""

#code
arr_col = 'arrival_time'
task5_airline = (df_airline.groupby(airline_col).agg(
    Total_Flights=(dep_col, 'count')
).reset_index())

print(task5_airline.head(5))

"""Task 6: Conditional Group Filtering"""

# code
task6_airline = df_airline.groupby(origin_col).filter(
    lambda x: x[dep_col].count() > 10000
)

print("Qualified Origin Airports:")
print(task6_airline[origin_col].unique())

print("Hub Flights Retained:", len(task6_airline))

"""Task 7: Derived Aggregate Metrics"""

#code
task7_airline = df_airline.groupby(airline_col).agg(
    Total_Flights=(dep_col, 'count')
).reset_index()

print(task7_airline.sort_values(by='Total_Flights', ascending=False).head(5))

"""Task 8: Extremum Selection with largest()"""

#code
task8_airline = df_airline.groupby(airline_col).size().nlargest(5).reset_index(name='Total_Flights')
print("Top 5 airlines by total flights:")
print(task8_airline)

"""Task 9: Quantile Aggregation"""

#code
task9_airline = df_airline.groupby(airline_col)[dep_col].value_counts().unstack(fill_value=0)
print("Departure Time Distribution by Airline (Counts):")
print(task9_airline.head(5))

"""Task 10: Frequency Counting via Groupby

Question: Identify the Top 10 busiest Origin-to-Destination flight routes by total flight volume.
"""

#code
task10_airline = (df_airline.groupby([origin_col, dest_col])
                  .size()
                  .reset_index(name='Flight_Count')
                  .sort_values(by='Flight_Count', ascending=False)
                  .head(10))

print(task10_airline)

"""Day 6&7

Task 6(i): Importing Libraries and Loading Airline Flights Dataset
"""

# AIRLINE  DATASET

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohitgrewal/airlines-flights-data")

print("Path to dataset files:", path)


import os

print(os.listdir(path))


import pandas as pd

df = pd.read_csv(os.path.join(path, "airlines_flights_data.csv"))

print( "Dataset loaded successfully")

import kagglehub
import pandas as pd
import os

# Download the exact dataset
path = kagglehub.dataset_download("rohitgrewal/airlines-flights-data")

print("Dataset path:", path)
print("Files:", os.listdir(path))

# Load CSV
df_airline = pd.read_csv(
    os.path.join(path, "airlines_flights_data.csv")
)
print(df_airline.columns.tolist())
print("Dataset loaded successfully")
print(df_airline.head())
print(df_airline.info())
print(df_airline.columns.tolist())

"""Task 1: Single-Column GroupBy Aggregation"""

airline_col = 'airline'
dep_col = 'departure_time'
origin_col = 'source city'
dest_col = 'destination city'

task1_airline = df_airline.groupby(airline_col)[dep_col].count().reset_index()
print(task1_airline.head(5))

"""Task 2: Multi-Column GroupBy Aggregation"""

# Task 2: Multi-Column GroupBy Aggregation

task2_airline = df_airline.groupby(
    ['source_city', 'destination_city']
).agg(
    Flight_Count=('flight', 'count')
).reset_index()

print(task2_airline.head(5))

"""Task 3: Multi-Metric Aggregation with agg()"""

# Code
task3_airline = df_airline.groupby(airline_col).agg(
    Total_Flights=(dep_col, 'count')
).reset_index()

print(task3_airline.head(5))

"""Task 4: Sorting Aggregated Summaries"""

# Task 4: Sorting Aggregated Summaries

task4_airline = (df_airline.groupby('source_city')
                 .size()
                 .reset_index(name='Total_Flights')
                 .sort_values(by='Total_Flights', ascending=False)
                 .head(5))

print(task4_airline)

"""Task 5: Named Aggregations"""

# Task 5: Named Aggregations

task5_airline = (
    df_airline.groupby('airline')
    .agg(
        Total_Flights=('flight', 'count'),
        Avg_Departure_Delay=('departure_time', 'count'),
        Avg_Arrival_Delay=('arrival_time', 'count')
    )
    .reset_index()
)

print(task5_airline.head(5))

"""Task 6: Conditional Group Filtering"""

# Task 6: Conditional Group Filtering

task6_airline = (
    df_airline.groupby('source_city')
    .filter(lambda x: len(x) > 10000)
)

print("Qualified Hub Airports:",
      task6_airline['source_city'].unique())

print("Hub Flights Retained:", len(task6_airline))

# First check your column names
print(df_airline.columns.tolist())

# Define correct columns
origin_col = 'source_city'
dest_col = 'destination_city'

# Now run Task 10
task10_airline = (df_airline.groupby([origin_col, dest_col])
                  .size()
                  .reset_index(name='Flight_Count')
                  .sort_values(by='Flight_Count', ascending=False)
                  .head(10))

print(task10_airline)

"""Day6&7"""

df_airline['Price_Difference'] = df_airline['price'] - df_airline['Avg_Airline_Price']
display(df_airline.head())

pivot_table = pd.pivot_table(df_airline, index='source_city', columns='class', values='price', aggfunc='mean')
display(pivot_table)

bins = [0, 6, 12, df_airline['duration'].max()]
labels = ['Short Haul', 'Medium Haul', 'Long Haul']
df_airline['Flight_Category'] = pd.cut(df_airline['duration'], bins=bins, labels=labels, right=False)
display(df_airline.head())

df_airline['Flight_Prefix'] = df_airline['flight'].str.split('-').str[0]
display(df_airline.head())

median_price = df_airline['price'].median()

filtered_flights = df_airline[
    (df_airline['departure_time'].isin(['Early_Morning', 'Morning'])) &
    (df_airline['price'] > median_price)
]

display(filtered_flights.head())

df_airline['Route'] = df_airline['source_city'] + ' -> ' + df_airline['destination_city']
display(df_airline.head())

df_airline['Price_Rank_Within_Airline'] = df_airline.groupby('airline')['price'].rank(ascending=False, method='min')
display(df_airline.sort_values(by=['airline', 'Price_Rank_Within_Airline']).head())

cross_tab_flights_stops = pd.crosstab(df_airline['airline'], df_airline['stops'])
display(cross_tab_flights_stops)

top_longest_flights = df_airline.groupby('airline').apply(lambda x: x.nlargest(3, 'duration')).reset_index(drop=True)
display(top_longest_flights)

"""Day 8&9

*Task: Compute Correlation Matrix for Duration, Price, and Stops and Plot Heatmap*

*AI Prompt for Code Generation:* "Compute correlation matrix for duration, price, and stops in df_flights and plot heatmap.
"""

# AIRLINE  DATASET

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohitgrewal/airlines-flights-data")

print("Path to dataset files:", path)


import os

print(os.listdir(path))


import pandas as pd

df = pd.read_csv(os.path.join(path, "airlines_flights_data.csv"))

print( "Dataset loaded successfully")

import seaborn as sns
import matplotlib.pyplot as plt

# Create a copy to avoid modifying the original DataFrame if 'stops' is needed elsewhere in its original format
df_corr = df_airline.copy()

# Convert 'stops' to a numerical representation
stop_mapping = {'zero': 0, 'one': 1, 'two_or_more': 2}
df_corr['stops_numeric'] = df_corr['stops'].map(stop_mapping)

# Select numerical columns for correlation
correlation_data = df_corr[['duration', 'price', 'stops_numeric']]

# Compute the correlation matrix
correlation_matrix = correlation_data.corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap="coolwarm", linewidths=.5)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.histplot(df_airline['price'], kde=True)
plt.title('Distribution of Flight Prices with KDE Overlay')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 7))
sns.boxplot(x='airline', y='price', data=df_airline)
plt.title('Price Distribution Across Airlines')
plt.xlabel('Airline')
plt.ylabel('Price')
plt.xticks(rotation=45)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.violinplot(x='class', y='price', data=df_airline)
plt.title('Price Distribution Across Travel Class (Violin Plot)')
plt.xlabel('Travel Class')
plt.ylabel('Price')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 7))
sns.scatterplot(x='duration', y='price', hue='class', alpha=0.6, data=df_airline)
plt.title('Flight Duration vs. Price, by Class')
plt.xlabel('Duration (hours)')
plt.ylabel('Price')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Create a pivot table for mean price between source and destination cities
mean_price_matrix = df_airline.pivot_table(index='source_city', columns='destination_city', values='price', aggfunc='mean')

plt.figure(figsize=(10, 8))
sns.heatmap(mean_price_matrix, annot=True, fmt=".0f", cmap="viridis")
plt.title('Mean Flight Price between Source and Destination Cities')
plt.xlabel('Destination City')
plt.ylabel('Source City')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Calculate the average price for each departure time slot
average_price_by_departure = df_airline.groupby('departure_time')['price'].mean().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='departure_time', y='price', data=average_price_by_departure, palette='viridis', hue='departure_time', legend=False)
plt.title('Average Flight Price by Departure Time')
plt.xlabel('Departure Time')
plt.ylabel('Average Price')
plt.xticks(rotation=45)
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Create a copy to avoid modifying the original DataFrame if 'stops' is needed elsewhere in its original format
df_corr = df_airline.copy()

# Convert 'stops' to a numerical representation
stop_mapping = {'zero': 0, 'one': 1, 'two_or_more': 2}
df_corr['stops_numeric'] = df_corr['stops'].map(stop_mapping)

# Select numerical columns for correlation
correlation_data = df_corr[['duration', 'price', 'stops_numeric']]

# Compute the correlation matrix
correlation_matrix = correlation_data.corr()

# Plot heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Correlation Matrix of Flight Attributes')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 7))
sns.countplot(y='airline', data=df_airline, order=df_airline['airline'].value_counts().index, palette='viridis', hue='airline', legend=False)
plt.title('Number of Flights per Airline')
plt.xlabel('Number of Flights')
plt.ylabel('Airline')
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Define the order for the 'stops' column for better visualization
stops_order = ['zero', 'one', 'two_or_more']

# Create a catplot to compare flight prices across stops categorized by travel class
g = sns.catplot(x='stops', y='price', col='class', data=df_airline, kind='box',
                order=stops_order, height=6, aspect=0.8, palette='viridis', hue='stops', legend=False)

g.set_axis_labels("Number of Stops", "Price")
g.set_titles("{col_name} Class")
plt.suptitle('Flight Price Distribution across Stops by Travel Class', y=1.02) # Adjust subtitle position
plt.show()

df_airline['Rolling_Mean_Price'] = df_airline['price'].rolling(window=100).mean()
display(df_airline.head())

"""Day 10&11"""

# AIRLINE  DATASET

import kagglehub

# Download latest version
path = kagglehub.dataset_download("rohitgrewal/airlines-flights-data")

print("Path to dataset files:", path)


import os

print(os.listdir(path))


import pandas as pd

df = pd.read_csv(os.path.join(path, "airlines_flights_data.csv"))

print( "Dataset loaded successfully")

import plotly.express as px

fig = px.histogram(df_airline, x='price', color='class', marginal='box',
                   hover_data=df_airline.columns,
                   title='Interactive Flight Price Distribution by Class')

fig.update_layout(bargap=0.1)
fig.show()

"""

*Task Topic:*
> *Task 2: Interactive 3D Scatter (Duration vs. Price vs. Days Left)*

*AI Prompt:* "Plot an interactive 3D scatter plot of duration, price, and days_left using http://px.scatter_3d."
"""

import plotly.express as px

# Check columns first
print(df_airline.columns.tolist())

fig = px.scatter_3d(df_airline,
                    x='duration',
                    y='price',
                    z='flight',
                    color='class',
                    symbol='airline',
                    title='3D Scatter - Duration vs Price vs Flight')

fig.update_layout(height=700)
fig.show()

import plotly.express as px

# Create a pivot table for mean price between source and destination cities
mean_price_matrix_plotly = df_airline.pivot_table(index='source_city', columns='destination_city', values='price', aggfunc='mean')

# Best for interactive matrix is px.imshow
fig = px.imshow(mean_price_matrix_plotly,
                text_auto='.0f',
                aspect="auto",
                color_continuous_scale='Viridis',
                title='Interactive Route Matrix: Avg Price by Source vs Destination')

fig.update_xaxes(side="top")
fig.show()

# Alternative if sir wants px.density_heatmap (long format):
# df_melted = mean_price_matrix_plotly.reset_index().melt(id_vars='source_city', var_name='destination_city', value_name='price')
# fig2 = px.density_heatmap(df_melted, x='source_city', y='destination_city', z='price', histfunc='avg', text_auto=True)
# fig2.show()

import plotly.express as px

fig = px.parallel_categories(df_airline, dimensions=['airline', 'source_city', 'class'],
                             title='Parallel Categories Diagram: Airline -> Source City -> Class')

fig.show()

import plotly.express as px

fig = px.scatter(df_airline,
                 x='duration',
                 y='price',
                 animation_frame='departure_time',
                 animation_group='flight', # Group by flight to ensure consistent animation of individual flights
                 color='class', # Color points by travel class
                 symbol='stops', # Use different symbols for number of stops
                 hover_data=['airline', 'source_city', 'destination_city'], # Display additional info on hover
                 title='Animated Scatter Plot: Price vs. Duration Across Departure Times',
                 log_y=True, # Logarithmic scale for price might be useful for better visualization of lower prices
                 size_max=10)

fig.show()

import plotly.express as px

fig = px.violin(df_airline, x='airline', y='price', color='class',
                box=True, # Show box plots inside the violins
                points='outliers', # Display outlier points
                title='Interactive Violin Plot of Flight Prices by Airline and Class',
                labels={'airline': 'Airline', 'price': 'Flight Price', 'class': 'Travel Class'})

fig.update_traces(quartilemethod='exclusive') # A common choice for quartile calculation
fig.show()

import plotly.express as px

# Aggregate the data to get the sum of prices for each unique path
df_treemap = df_airline.groupby(['airline', 'source_city', 'destination_city'])['price'].sum().reset_index()

fig = px.treemap(df_treemap,
                 path=['airline', 'source_city', 'destination_city'],
                 values='price',
                 color='price', # Color based on price
                 hover_data=['airline', 'source_city', 'destination_city', 'price'], # Show details on hover
                 title='Hierarchical Treemap: Airline -> Source City -> Destination City (Scaled by Price)',
                 color_continuous_scale='viridis') # Choose a color scale

fig.show()

import plotly.graph_objects as go

# Calculate the mean price for each airline
mean_price_by_airline = df_airline.groupby('airline')['price'].mean().reset_index()

# Create a Polar/Radar chart
fig = go.Figure(data=go.Scatterpolar(
    r=mean_price_by_airline['price'],
    theta=mean_price_by_airline['airline'],
    fill='toself',
    name='Mean Price'
))

fig.update_layout(
    polar=dict(
        radialaxis=dict(
            visible=True,
        ),
    ),
    title='Polar/Radar Chart: Mean Flight Price by Airline',
    showlegend=True
)

fig.show()

import plotly.express as px

fig = px.scatter(
    df_airline,
    x='duration',
    y='price',
    color='class',
    hover_name='flight',
    title='Interactive Scatter Plot with Custom Hover Template',
    labels={'duration': 'Duration (hours)', 'price': 'Flight Price'}
)

fig.show()

import plotly.graph_objects as go
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=2, subplot_titles=('Bar Chart', 'Scatter Plot'))

fig.add_trace(go.Bar(x=df_airline['airline'].value_counts().index, y=df_airline['airline'].value_counts().values), row=1, col=1)

fig.add_trace(go.Scatter(x=df_airline['duration'], y=df_airline['price'], mode='markers'), row=1, col=2)

fig.update_layout(title_text='Multi-Panel Interactive Subplots Container')
fig.show()